#! /usr/bin/env python
#
# root-me.org/Programming/ep1
import re
from math import sqrt
import socket, time
import base64

def pingpong():
    while 1:
        junk = b""
        junk = irc.recv(7000)
        print(junk)
        beg = junk.find(b"PING") # Get the index of "PING"
        if beg > -1:             # If PING is captured
            junk = junk[beg:]
            if junk[5:].find(b" ")>0: # Check if there is a data sent after "PING"
                junk = junk[:(junk[5:].find(b" "))+4]+b"\r\n" # If TRUE, strip the data
                                                            # to obtain only "PING" message
            junk = junk.replace(b"PING",b"PONG") # raplace "PING" with "PONG"
            irc.send(junk) # send back the "PONG" message
            irc.send(junk) # do it more than once to make sure it's received
            irc.send(junk)
            break

hote = "irc.root-me.org"
port = 6667
bot = "Candy"
channel = "#root-me_challenge"

id = "ep1"

irc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
irc.connect((hote, port))

irc.send("NICK Glazic2 \r\n")
irc.send("USER Glazic2 " + hote + " root-me :My Bot \r\n")
irc.send("JOIN " + channel)

pingpong()

irc.send("PRIVMSG Candy !ep1 \r\n")
message = irc.recv(1024)
final = 0.0
tab_message = []

while (message.find("Candy!Candy@root") == -1) :
    irc.send("PRIVMSG Candy !ep1 \r\n")
    message = irc.recv(1024)
    tab_message.append(message)

if(len(tab_message)>1):
    message = tab_message[1]
    print(message)
    nombres = message.split(":")[2]
    print(nombres)
    a, b = nombres.split(" / ")
    nombre_final = round(sqrt(int(a))*int(b), 2)
    print("Final = "+str(nombre_final))
    irc.send("PRIVMSG Candy :!ep2 -rep " + str(final) + " \r\n")
    print(irc.recv(1024))

else :
    message = tab_message[0]
    print(message)
    nombres = message.split(":")[2]
    print(nombres)
    a, b = nombres.split(" / ")
    nombre_final = round(sqrt(int(a)) *int(b), 2)
    print("Final = "+str(nombre_final))
    irc.send("PRIVMSG Candy :!ep2 -rep " + str(final) + " \r\n")
    print(irc.recv(1024))
